In [36]:
import numpy as np
import pandas as pd

In [37]:
data = pd.read_csv('pima-indians-diabetes.csv')
data.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [38]:
data = pd.read_csv('pima-indians-diabetes.csv', names=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age','class'])

In [39]:
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [40]:
data.isnull()

preg   plas   pres   skin   test   mass   pedi    age  class
0    False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...
763  False  False  False  False  False  False  False  False  False
764  False  False  False  False  False  False  False  False  False
765  False  False  False  False  False  False  False  False  False
766  False  False  False  False  False  False  False  False  False
767  False  False  False  False  False  False  False  False  False

[768 rows x 9 columns]

In [41]:
data.isnull().sum()

preg     0
plas     0
pres     0
skin     0
test     0
mass     0
pedi     0
age      0
class    0
dtype: int64

In [42]:
Skins = data[data['skin'] == 0]
Skins

preg  plas  pres  skin  test  mass   pedi  age  class
2       8   183    64     0     0  23.3  0.672   32      1
5       5   116    74     0     0  25.6  0.201   30      0
7      10   115     0     0     0  35.3  0.134   29      0
9       8   125    96     0     0   0.0  0.232   54      1
10      4   110    92     0     0  37.6  0.191   30      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
757     0   123    72     0     0  36.3  0.258   52      1
758     1   106    76     0     0  37.5  0.197   26      0
759     6   190    92     0     0  35.5  0.278   66      1
762     9    89    62     0     0  22.5  0.142   33      0
766     1   126    60     0     0  30.1  0.349   47      1

[227 rows x 9 columns]

In [43]:
len(data)

768

In [44]:
data['skin'].mean()

20.536458333333332

In [45]:
skin_mean = data[data['skin'] !=0]['skin'].mean()
skin_mean

29.153419593345657

In [46]:
data[data['skin'] == 0]['skin'] = data[data['skin'] !=0]['skin'].mean()

<ipython-input-46-c65a677fd084>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[data['skin'] == 0]['skin'] = data[data['skin'] !=0]['skin'].mean()


In [47]:
data.replace({'skin':0}, skin_mean, inplace=True)

In [48]:
test_mean = data[data['test'] != 0]['test'].mean()

In [49]:
data.replace({'test':0}, test_mean, inplace = True)

In [50]:
data


preg  plas  pres      skin        test  mass   pedi  age  class
0       6   148    72  35.00000  155.548223  33.6  0.627   50      1
1       1    85    66  29.00000  155.548223  26.6  0.351   31      0
2       8   183    64  29.15342  155.548223  23.3  0.672   32      1
3       1    89    66  23.00000   94.000000  28.1  0.167   21      0
4       0   137    40  35.00000  168.000000  43.1  2.288   33      1
..    ...   ...   ...       ...         ...   ...    ...  ...    ...
763    10   101    76  48.00000  180.000000  32.9  0.171   63      0
764     2   122    70  27.00000  155.548223  36.8  0.340   27      0
765     5   121    72  23.00000  112.000000  26.2  0.245   30      0
766     1   126    60  29.15342  155.548223  30.1  0.349   47      1
767     1    93    70  31.00000  155.548223  30.4  0.315   23      0

[768 rows x 9 columns]

In [51]:
data.replace({'test':0, 'skin':0}, np.nan, inplace = True)

In [52]:
data


preg  plas  pres      skin        test  mass   pedi  age  class
0       6   148    72  35.00000  155.548223  33.6  0.627   50      1
1       1    85    66  29.00000  155.548223  26.6  0.351   31      0
2       8   183    64  29.15342  155.548223  23.3  0.672   32      1
3       1    89    66  23.00000   94.000000  28.1  0.167   21      0
4       0   137    40  35.00000  168.000000  43.1  2.288   33      1
..    ...   ...   ...       ...         ...   ...    ...  ...    ...
763    10   101    76  48.00000  180.000000  32.9  0.171   63      0
764     2   122    70  27.00000  155.548223  36.8  0.340   27      0
765     5   121    72  23.00000  112.000000  26.2  0.245   30      0
766     1   126    60  29.15342  155.548223  30.1  0.349   47      1
767     1    93    70  31.00000  155.548223  30.4  0.315   23      0

[768 rows x 9 columns]

In [53]:
from sklearn.impute import KNNImputer

In [54]:
imputer = KNNImputer(n_neighbors = 3)

In [55]:
data = imputer.fit_transform(data)
data

array([[6.00000000e+00, 1.48000000e+02, 7.20000000e+01, 3.50000000e+01,
        1.55548223e+02, 3.36000000e+01, 6.27000000e-01, 5.00000000e+01,
        1.00000000e+00],
       [1.00000000e+00, 8.50000000e+01, 6.60000000e+01, 2.90000000e+01,
        1.55548223e+02, 2.66000000e+01, 3.51000000e-01, 3.10000000e+01,
        0.00000000e+00],
       [8.00000000e+00, 1.83000000e+02, 6.40000000e+01, 2.91534196e+01,
        1.55548223e+02, 2.33000000e+01, 6.72000000e-01, 3.20000000e+01,
        1.00000000e+00],
       [1.00000000e+00, 8.90000000e+01, 6.60000000e+01, 2.30000000e+01,
        9.40000000e+01, 2.81000000e+01, 1.67000000e-01, 2.10000000e+01,
        0.00000000e+00],
       [0.00000000e+00, 1.37000000e+02, 4.00000000e+01, 3.50000000e+01,
        1.68000000e+02, 4.31000000e+01, 2.28800000e+00, 3.30000000e+01,
        1.00000000e+00],
       [5.00000000e+00, 1.16000000e+02, 7.40000000e+01, 2.91534196e+01,
        1.55548223e+02, 2.56000000e+01, 2.01000000e-01, 3.00000000e+01,
        0.0

In [56]:
type(data)

numpy.ndarray

In [57]:
import sys

In [58]:
np.set_printoptions(threshold = sys.maxsize)
print(data)

[[6.00000000e+00 1.48000000e+02 7.20000000e+01 3.50000000e+01
  1.55548223e+02 3.36000000e+01 6.27000000e-01 5.00000000e+01
  1.00000000e+00]
 [1.00000000e+00 8.50000000e+01 6.60000000e+01 2.90000000e+01
  1.55548223e+02 2.66000000e+01 3.51000000e-01 3.10000000e+01
  0.00000000e+00]
 [8.00000000e+00 1.83000000e+02 6.40000000e+01 2.91534196e+01
  1.55548223e+02 2.33000000e+01 6.72000000e-01 3.20000000e+01
  1.00000000e+00]
 [1.00000000e+00 8.90000000e+01 6.60000000e+01 2.30000000e+01
  9.40000000e+01 2.81000000e+01 1.67000000e-01 2.10000000e+01
  0.00000000e+00]
 [0.00000000e+00 1.37000000e+02 4.00000000e+01 3.50000000e+01
  1.68000000e+02 4.31000000e+01 2.28800000e+00 3.30000000e+01
  1.00000000e+00]
 [5.00000000e+00 1.16000000e+02 7.40000000e+01 2.91534196e+01
  1.55548223e+02 2.56000000e+01 2.01000000e-01 3.00000000e+01
  0.00000000e+00]
 [3.00000000e+00 7.80000000e+01 5.00000000e+01 3.20000000e+01
  8.80000000e+01 3.10000000e+01 2.48000000e-01 2.60000000e+01
  1.00000000e+00]
 [1.00

In [69]:
data = data[: , :-1]
data

array([[ 6.39947260e-01,  8.48323795e-01,  1.49640753e-01,
         6.65502121e-01, -2.71787659e-16,  2.04012771e-01,
         4.68491977e-01],
       [-8.44885053e-01, -1.12339636e+00, -1.60545747e-01,
        -1.74633816e-02, -2.71787659e-16, -6.84421946e-01,
        -3.65060778e-01],
       [ 1.23388019e+00,  1.94372388e+00, -2.63941247e-01,
         0.00000000e+00, -2.71787659e-16, -1.10325546e+00,
         6.04397318e-01],
       [-8.44885053e-01, -9.98207780e-01, -1.60545747e-01,
        -7.00428884e-01, -7.24388738e-01, -4.94043078e-01,
        -9.20762614e-01],
       [-1.14185152e+00,  5.04055196e-01, -1.50468724e+00,
         6.65502121e-01,  1.46550563e-01,  1.40974560e+00,
         5.48490910e+00],
       [ 3.42980797e-01, -1.53184856e-01,  2.53036252e-01,
         0.00000000e+00, -2.71787659e-16, -8.11341192e-01,
        -8.18078579e-01],
       [-2.50952128e-01, -1.34247638e+00, -9.87709745e-01,
         3.24019370e-01, -7.95005438e-01, -1.25977267e-01,
        -6.7613300

In [70]:
from sklearn.preprocessing import MinMaxScaler

In [71]:
scaler = MinMaxScaler(feature_range = (0,1))

In [72]:
data = scaler.fit_transform(data)

In [73]:
data

array([[0.35294118, 0.74371859, 0.59016393, 0.30434783, 0.17013008,
        0.50074516, 0.23441503],
       [0.05882353, 0.42713568, 0.54098361, 0.23913043, 0.17013008,
        0.39642325, 0.11656704],
       [0.47058824, 0.91959799, 0.52459016, 0.24079804, 0.17013008,
        0.34724292, 0.25362938],
       [0.05882353, 0.44723618, 0.54098361, 0.17391304, 0.09615385,
        0.41877794, 0.03800171],
       [0.        , 0.68844221, 0.32786885, 0.30434783, 0.18509615,
        0.64232489, 0.94363792],
       [0.29411765, 0.58291457, 0.60655738, 0.24079804, 0.17013008,
        0.38152012, 0.05251921],
       [0.17647059, 0.3919598 , 0.40983607, 0.27173913, 0.08894231,
        0.46199702, 0.07258753],
       [0.58823529, 0.57788945, 0.        , 0.24079804, 0.17013008,
        0.52608048, 0.02391119],
       [0.11764706, 0.98994975, 0.57377049, 0.41304348, 0.63581731,
        0.45454545, 0.03415884],
       [0.47058824, 0.6281407 , 0.78688525, 0.24079804, 0.17013008,
        0.        , 0.0

In [74]:
from sklearn.preprocessing import StandardScaler

In [75]:
scaler = StandardScaler()

In [76]:
data = scaler.fit_transform(data)

In [77]:
data

array([[ 6.39947260e-01,  8.48323795e-01,  1.49640753e-01,
         6.65502121e-01,  0.00000000e+00,  2.04012771e-01,
         4.68491977e-01],
       [-8.44885053e-01, -1.12339636e+00, -1.60545747e-01,
        -1.74633816e-02,  0.00000000e+00, -6.84421946e-01,
        -3.65060778e-01],
       [ 1.23388019e+00,  1.94372388e+00, -2.63941247e-01,
         0.00000000e+00,  0.00000000e+00, -1.10325546e+00,
         6.04397318e-01],
       [-8.44885053e-01, -9.98207780e-01, -1.60545747e-01,
        -7.00428884e-01, -7.24388738e-01, -4.94043078e-01,
        -9.20762614e-01],
       [-1.14185152e+00,  5.04055196e-01, -1.50468724e+00,
         6.65502121e-01,  1.46550563e-01,  1.40974560e+00,
         5.48490910e+00],
       [ 3.42980797e-01, -1.53184856e-01,  2.53036252e-01,
         0.00000000e+00,  0.00000000e+00, -8.11341192e-01,
        -8.18078579e-01],
       [-2.50952128e-01, -1.34247638e+00, -9.87709745e-01,
         3.24019370e-01, -7.95005438e-01, -1.25977267e-01,
        -6.7613300

In [79]:
from sklearn.preprocessing import Normalizer

In [80]:
norm = Normalizer()

In [81]:
data = norm.fit_transform(data)
data

array([[ 4.69790985e-01,  6.22762055e-01,  1.09852610e-01,
         4.88551036e-01,  0.00000000e+00,  1.49767593e-01,
         3.43924134e-01],
       [-5.23609791e-01, -6.96214629e-01, -9.94967594e-02,
        -1.08227712e-02,  0.00000000e+00, -4.24164247e-01,
        -2.26243081e-01],
       [ 4.67948007e-01,  7.37155623e-01, -1.00099492e-01,
         0.00000000e+00,  0.00000000e+00, -4.18408690e-01,
         2.29217167e-01],
       [-4.30971457e-01, -5.09180580e-01, -8.18935477e-02,
        -3.57285119e-01, -3.69506915e-01, -2.52008796e-01,
        -4.69676205e-01],
       [-1.89369431e-01,  8.35946218e-02, -2.49543625e-01,
         1.10369655e-01,  2.43045582e-02,  2.33798106e-01,
         9.09640264e-01],
       [ 2.77043191e-01, -1.23735269e-01,  2.04390366e-01,
         0.00000000e+00,  0.00000000e+00, -6.55361916e-01,
        -6.60804049e-01],
       [-1.24686206e-01, -6.67012819e-01, -4.90746111e-01,
         1.60989852e-01, -3.95000484e-01, -6.25921268e-02,
        -3.3593841

In [85]:
from sklearn.preprocessing import Binarizer

In [87]:
binarizer = Binarizer(threshold = 0.0)
data_b = binarizer.fit_transform(data)

In [90]:
data_b

array([[1., 1., 1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 1., 1., 1.],
       [1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1., 1.],
       [1., 1., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0.],
       [1., 1., 1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 0., 1., 0.],
       [1., 1., 1., 0., 0., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 1., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 1., 0.],
 

In [92]:
np.concatenate((data, data_b), axis = 1)

array([[ 4.69790985e-01,  6.22762055e-01,  1.09852610e-01,
         4.88551036e-01,  0.00000000e+00,  1.49767593e-01,
         3.43924134e-01,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00],
       [-5.23609791e-01, -6.96214629e-01, -9.94967594e-02,
        -1.08227712e-02,  0.00000000e+00, -4.24164247e-01,
        -2.26243081e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 4.67948007e-01,  7.37155623e-01, -1.00099492e-01,
         0.00000000e+00,  0.00000000e+00, -4.18408690e-01,
         2.29217167e-01,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00],
       [-4.30971457e-01, -5.09180580e-01, -8.18935477e-02,
        -3.57285119e-01, -3.69506915e-01, -2.52008796e-01,
        -4.69676205e-01,  0.00000000e+00,  0.